import Navbar from "@/components/Navbar/Navbar";
import "./globals.css";
import ShowButton from "@/components/ShowButton/ShowButton";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        <ShowButton/>
            {children}
      </body>
    </html>
  );
}
